name: Release

# This GitHub Action workflow is triggered when a new tag with v prefix is pushed.
on:
  push:
    tags:
      - "v*"

permissions:
  contents: write

jobs:
  create-release:
    name: Create release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v7.0.1
        with:
          fetch-depth: 0

      - name: Install Cocogito
        uses: cocogitto/cocogitto-action@v4.1.0
        with:
          command: get-version

      - name: Generate Changelog
        run: cog changelog --at ${{ github.ref_name }} -t full_hash > GITHUB_CHANGELOG.md

      - name: Upload github release
        uses: softprops/action-gh-release@v3.0.2
        with:
          body_path: GITHUB_CHANGELOG.md
          tag_name: ${{ github.ref_name }}
